version: '3.7'

services:
  db:
    image: postgres:12.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: dev_pass
    ports:
      - 5432:5432
    networks:
      public:

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    networks:
      public:

networks:
  public:
    driver: bridge
